"""
Persona-based Customer Data Generator

Generates synthetic customer profiles based on the 6 defined personas,
linked to their actual review/purchase data for evaluation.
"""

import json
import pandas as pd
import numpy as np
import uuid
from collections import defaultdict

# Persona Definitions
PERSONAS = {
    0: {"name": "Dry_Winter", "name_kr": "건성/겨울보습형", "skin_type": "dry", "concern": "moisture"},
    1: {"name": "Anti_Aging", "name_kr": "안티에이징형", "skin_type": "mature", "concern": "wrinkle"},
    2: {"name": "Gift_Buyer", "name_kr": "선물구매형", "skin_type": "unknown", "concern": "gift"},
    3: {"name": "Loyal_Repurchase", "name_kr": "충성리피터", "skin_type": "normal", "concern": "repurchase"},
    4: {"name": "Sensitive_Calming", "name_kr": "민감진정형", "skin_type": "sensitive", "concern": "calming"},
    5: {"name": "Detail_Reviewer", "name_kr": "성분분석형", "skin_type": "combination", "concern": "texture"},
}

# Category Mapping
CATEGORIES = {
    97: "Skincare",
    98: "Makeup",
    99: "Perfume", 
    101: "Accessories",
    103: "Men"
}

def generate_customer_data():
    """
    Creates customers.json with:
    - user_id (UUID)
    - persona_id (0-5)
    - persona_name
    - age (simulated)
    - gender (simulated)
    - skin_type
    - skin_concern
    - purchased_products (from actual review data)
    - reviewed_products (same as purchased for our data)
    """
    
    # Load labeled reviews (generated by clustering.py, saved in amore_project/)
    # Try multiple possible locations
    import os
    possible_paths = ['labeled_reviews.csv', '../labeled_reviews.csv', 'neural_recsys/labeled_reviews.csv']
    df = None
    for path in possible_paths:
        if os.path.exists(path):
            df = pd.read_csv(path)
            break
    if df is None:
        raise FileNotFoundError("labeled_reviews.csv not found! Run clustering.py first.")
    
    customers = []
    
    # Group by cluster to create one customer per unique reviewer pattern
    # Since we don't have real user IDs, each review = one customer instance
    for idx, row in df.iterrows():
        cluster = row['cluster']
        persona = PERSONAS[cluster]
        
        # Simulate demographics based on persona
        if cluster in [0, 1]:  # Dry_Winter, Anti_Aging → older
            age = np.random.randint(35, 50)
        elif cluster in [3, 5]:  # Loyal, Detail → 20-30s
            age = np.random.randint(25, 38)
        else:
            age = np.random.randint(20, 45)
            
        gender = "F" if cluster != 103 else "M"  # Men's category
        
        customer = {
            "user_id": f"user_{idx:04d}",
            "persona_id": cluster,
            "persona_name": persona["name"],
            "persona_name_kr": persona["name_kr"],
            "age": int(age),
            "gender": gender,
            "skin_type": persona["skin_type"],
            "skin_concern": persona["concern"],
            "purchased_product_id": row["product_id"],
            "product_category": int(row["category"]),
            "product_category_name": CATEGORIES.get(int(row["category"]), "Unknown"),
            "review_content": row["content"][:200]  # Truncate for storage
        }
        customers.append(customer)
    
    # Save
    with open("data/customers.json", "w", encoding="utf-8") as f:
        json.dump(customers, f, ensure_ascii=False, indent=2)
    
    print(f"Generated {len(customers)} customer profiles → data/customers.json")
    
    # Summary
    df_cust = pd.DataFrame(customers)
    print("\n=== Persona Distribution ===")
    print(df_cust['persona_name'].value_counts())
    print("\n=== Category Distribution ===")
    print(df_cust['product_category_name'].value_counts())
    
    return customers

if __name__ == "__main__":
    generate_customer_data()
